stages:
  - install
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  APP_NAME: 'my-nextjs-app'
  AWS_ECR_REGISTRY: '123456789012.dkr.ecr.us-west-2.amazonaws.com' # Update with your AWS ECR registry
  AWS_REGION: 'us-west-2' # Update with your AWS region

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install -yqq git curl
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -yqq nodejs
  - npm install -g npm@latest

install_dependencies:
  stage: install
  script:
    - npm ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next
      - out

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to S3 or any other platform" # Replace with actual deployment script
    # Example for deploying to S3:
    # - aws s3 sync out/ s3://your-bucket-name --region $AWS_REGION
